version: '3'

services: 
  redis-server:
    image: 'redis'
  fm-backend-stub:
    build: ./backend-stub
    ports:
      - "8000:8080"
  feedback-module:
    build: ./feedback-module
    container_name: feedback-module
    volumes:
      - './feedback-module:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  fm-webpage:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./homepage:/usr/share/nginx/html
